#ifndef __SOCKTEST__H
#define __SOCKTEST__H

#define SOCKOPT_BASE        10086
#define SOCKOPT_SET_MIN     SOCKOPT_BASE+1
#define SOCKOPT_SET_BUFFER  SOCKOPT_BASE+1
#define SOCKOPT_SET_MAX     SOCKOPT_BASE+2

#define SOCKOPT_GET_MIN     SOCKOPT_BASE+1
#define SOCKOPT_GET_BUFFER  SOCKOPT_BASE+1
#define SOCKOPT_GET_MAX     SOCKOPT_BASE+2


#endif
